<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="reg.aspx.cs" Inherits="practice.WebForm1" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style type="text/css">
        .auto-style1 {
            height: 29px;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <table border="1" align="center">
                <tr>
                    <td>Enter A Id:</td>
                    <td>
                        <asp:TextBox ID="txtid" runat="server" TextMode="Number"></asp:TextBox></td>
                </tr>
                <tr>
                    <td>FirstName:</td>
                    <td>
                        <asp:TextBox ID="txtfirst" runat="server"></asp:TextBox></td>
                </tr>
                <tr>
    <td>LastName:</td>
    <td>
        <asp:TextBox ID="txtlastnm" runat="server"></asp:TextBox></td>
</tr>
                <tr>
    <td>E-mail</td>
    <td>
        <asp:TextBox ID="txtmail" runat="server" TextMode="Email"></asp:TextBox></td>
</tr>
                <tr>
                    <td>Gender</td>
                    <td>
                        <asp:RadioButton ID="rdmale" runat="server" Text="male" GroupName="rblgender" /><asp:RadioButton ID="rdfemale" runat="server" Text="female"  GroupName="rblgender"/></td>
                </tr>
                <tr>
    <td>Hobbies</td>
    <td>
        <asp:CheckBox ID="chkread" runat="server" Text="Reading" /><asp:CheckBox ID="chkwrite" runat="server" Text="writting" /><asp:CheckBox ID="chkgym" runat="server"  Text="Gyming"/></td>
</tr>
                <tr>
    <td class="auto-style1">Dob</td>
    <td class="auto-style1">
        <asp:TextBox ID="dob" runat="server" TextMode="Date"></asp:TextBox></td>
</tr>
                <tr>
    <td>Category</td>
         <td>
             <asp:DropDownList ID="ddlcategory" runat="server">
                 <asp:ListItem Selected="True">Selected</asp:ListItem>
                 <asp:ListItem>Sc</asp:ListItem>
                 <asp:ListItem>St</asp:ListItem>
                 <asp:ListItem>OBC</asp:ListItem>
                 <asp:ListItem>EWS</asp:ListItem>
             </asp:DropDownList></td>
</tr>
              
                <tr>
    <td colspan="3" align="center">
        <asp:Button ID="insert" runat="server" Text="insert" OnClick="insert_Click" /><asp:Button ID="delete" runat="server" Text="delete" OnClick="delete_Click" /><asp:Button ID="update" runat="server" Text="update" OnClick="update_Click" />
        <br />
        <br />
        <br />
        <br />
        <asp:GridView ID="GridView1" runat="server" AutoGenerateDeleteButton="True" DataKeyNames="id" OnRowDeleting="GridView1_RowDeleting">
            <Columns>
                <asp:ButtonField CommandName="Delete" Text="Delete" />
                <asp:ButtonField CommandName="Select" Text="Select" />
                <asp:ButtonField CommandName="Edit" Text="Edit" />
            </Columns>
            <SelectedRowStyle BackColor="yellow" />
        </asp:GridView>
        <br />
        <br />
        <br />
        Searching :<asp:TextBox ID="txtsearch" runat="server"></asp:TextBox> <asp:Button ID="search" runat="server" Text="search" OnClick="search_Click" />
                    <br />
        <br />
        <asp:GridView ID="GridView2" runat="server">
            <Columns>
                <asp:ButtonField CommandName="Delete" Text="Delete" />
            </Columns>
        </asp:GridView>
                    </td>
    <td></td>
</tr>
            </table>

        </div>
    </form>
</body>
</html>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Data.SqlClient;
using System.Configuration;
using System.Data;

namespace practice
{
    public partial class WebForm1 : System.Web.UI.Page
    {
        string connectionstring = ConfigurationManager.ConnectionStrings["ConnectionString"].ConnectionString;
        protected void Page_Load(object sender, EventArgs e)
        {
            if (!IsPostBack)
            {
                bindgrid();
            }

        }
        void bindgrid()
        {
            SqlConnection con = new SqlConnection(connectionstring);
            string query = "select * from Registration";
            SqlCommand cmd= new SqlCommand(query, con);
            con.Open();
            GridView1.DataSource= cmd.ExecuteReader();
            GridView1.DataBind();
            con.Close();


        }

        protected void insert_Click(object sender, EventArgs e)
        {
            string gender = "";
            if (rdmale.Checked)
            {
                gender = "male";
            }
            else if (rdfemale.Checked) {
                gender = "female";
            }
            string hobbies = "";
            if ((chkread.Checked))
            {
                hobbies += "reading";
            }
            if ((chkwrite.Checked))
            {
                hobbies += "writting";
            }
            if (chkgym.Checked)
            {
                hobbies += "gyming";
            }


            SqlConnection con = new SqlConnection(connectionstring);
            string query = "insert into Registration (firstname,lastname,email,gender,hobby,dob,category) values (@firstname,@lastname,@email,@gender,@hobby,@dob,@category)";
            SqlCommand cmd = new SqlCommand(query, con);
            con.Open();
            cmd.Parameters.AddWithValue("firstname",txtfirst.Text);
            cmd.Parameters.AddWithValue("lastname", txtlastnm.Text);
            cmd.Parameters.AddWithValue("email", txtmail.Text);
            cmd.Parameters.AddWithValue("gender", gender);
            cmd.Parameters.AddWithValue("hobby", hobbies);
            cmd.Parameters.AddWithValue("dob", dob.Text);
            cmd.Parameters.AddWithValue("category", ddlcategory.SelectedItem.Value);
          

            cmd.ExecuteNonQuery();
            bindgrid();


        }

        protected void delete_Click(object sender, EventArgs e)
        {
            SqlConnection con = new SqlConnection(connectionstring);
            string query = "delete from Registration where id=@id";
            SqlCommand cmd = new SqlCommand(query, con);
            cmd.Parameters.AddWithValue("@id", txtid.Text);
            con.Open();

           int row =cmd.ExecuteNonQuery();
            if(row > 0)
            {
                Response.Write("delete succesfully");
            }
            else
            {
                Response.Write("delete not succesfully");
            }
            bindgrid();
        }

        protected void update_Click(object sender, EventArgs e)
        {
            string gender = "";
            if (rdmale.Checked)
            {
                gender = "male";
            }
            else if (rdfemale.Checked)
            {
                gender = "female";
            }
            string hobbies = "";
            if ((chkread.Checked))
            {
                hobbies += "reading";
            }
            if ((chkwrite.Checked))
            {
                hobbies += "writting";
            }
            if (chkgym.Checked)
            {
                hobbies += "gyming";
            }
            SqlConnection con = new SqlConnection(connectionstring);
            string query = "update  Registration set firstname=@firstname,lastname=@lastname,email=@email,gender=@gender,hobby=@hobby,dob=@dob,category=@category where id=@id";
            SqlCommand cmd = new SqlCommand(query, con);
            con.Open();
            cmd.Parameters.AddWithValue("id", txtid.Text);
            cmd.Parameters.AddWithValue("firstname", txtfirst.Text);
            cmd.Parameters.AddWithValue("lastname", txtlastnm.Text);
            cmd.Parameters.AddWithValue("email", txtmail.Text);
            cmd.Parameters.AddWithValue("gender", gender);
            cmd.Parameters.AddWithValue("hobby", hobbies);
            cmd.Parameters.AddWithValue("dob", dob.Text);
            cmd.Parameters.AddWithValue("category", ddlcategory.SelectedItem.Value);


            int row = cmd.ExecuteNonQuery();
            if (row > 0)
            {
                Response.Write("update succesfully");
            }
            else
            {
                Response.Write("update not succesfully");
            }
            bindgrid();
        }

        protected void GridView1_RowDeleting(object sender, GridViewDeleteEventArgs e)
        {
            int id=(int) GridView1.DataKeys[e.RowIndex].Value;
            SqlConnection con = new SqlConnection(connectionstring);
            string query = "delete from Registration where id=@id";
            SqlCommand cmd = new SqlCommand(query, con);
            cmd.Parameters.AddWithValue("@id",id);
            con.Open();

            int row = cmd.ExecuteNonQuery();
          
            bindgrid();
        }
         void searching( string nm="-1")
        {
            SqlConnection con = new SqlConnection(connectionstring);    
            DataSet ds = new DataSet();
            SqlDataAdapter da = new SqlDataAdapter("select * from Registration where firstname like '%" + nm  +"%'" , con);
             da.Fill(ds);
            GridView2.DataSource = ds;  
            GridView2.DataBind();
        }
        protected void search_Click(object sender, EventArgs e)
        {
            try
            {
                searching(txtsearch.Text);
            }
            catch (Exception ex)
            {

                Response.Write(ex.Message);
            }
          
        }
    }
    }
